version: '3'
services:
  db-product:
    container_name: db-product
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce_products
      POSTGRES_USER: privado11
      POSTGRES_PASSWORD: privado
      
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431
  
  db-user:
    container_name: db-user
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce_users
      POSTGRES_USER: privado11
      POSTGRES_PASSWORD: privado
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432

  db-order:
    container_name: db-order
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: ecommerce_orders
      POSTGRES_USER: privado11
      POSTGRES_PASSWORD: privado
    ports:
      - 5433:5433
    expose:
      - 5433
    command: -p 5433

  db-keycloak:
    container_name: db-keycloak
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: privado11
      POSTGRES_PASSWORD: privado
    ports:
      - 5434:5434
    expose:
      - 5434
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: -p 5434

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: ["start-dev", "--import-realm"]
    ports:
      - 8181:8181
    expose:
      - 8181
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/  
      - keycloak_data:/opt/keycloak/data
    restart: unless-stopped
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5434
      DB_USER: privado11
      DB_PASSWORD: privado
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181

volumes:
  postgres_data:
  keycloak_data: